# Generated by Django 4.0.4 on 2022-05-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_has_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='has_profile',
        ),
    ]
