# Generated by Django 4.0.4 on 2022-05-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_appuser_has_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
    ]
