# Generated by Django 4.0.4 on 2022-05-12 13:34

import django.core.validators
from django.db import migrations, models
import habibas_blog.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appuser_has_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[habibas_blog.common.validators.MinDateValidator('01-01-1920'), habibas_blog.common.validators.MaxDateValidator('01-01-2017')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[habibas_blog.common.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_local',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images', validators=[habibas_blog.common.validators.MaxFileSizeInMbImageValidator(5)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[habibas_blog.common.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)]),
        ),
    ]
