# Generated by Django 4.0.4 on 2022-05-16 13:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_local',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
