# Generated by Django 4.0.4 on 2022-05-16 14:16

from django.db import migrations, models
import habibas_blog.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_image_profile_image_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_local',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images', validators=[habibas_blog.common.validators.MaxFileSizeInMbImageValidator(5)]),
        ),
    ]
