# Generated by Django 4.0.4 on 2022-05-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catchy_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
