# Generated by Django 4.0.4 on 2022-05-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogowner_remove_comment_likes_alter_comment_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='post',
            new_name='comment',
        ),
    ]
