# Generated by Django 4.0.4 on 2022-05-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_post_commentlike_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGalley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('local_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('url_image', models.URLField(blank=True, null=True)),
                ('cover_image', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
