# Generated by Django 4.0.4 on 2022-05-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_imagegallery_delete_imagegalley'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='url_image',
        ),
    ]
