# Generated by Django 4.0.4 on 2022-05-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_imagegallery_local_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
    ]
