# Generated by Django 4.0.4 on 2022-05-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ownerarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerarticle',
            name='right',
            field=models.BooleanField(default=True),
        ),
    ]
