# Generated by Django 4.0.4 on 2022-05-12 13:34

import django.core.validators
from django.db import migrations, models
import habibas_blog.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ownerarticle_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogowner',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), habibas_blog.common.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='blogowner',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), habibas_blog.common.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='blogowner',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='owner_images', validators=[habibas_blog.common.validators.MaxFileSizeInMbImageValidator(5)]),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[habibas_blog.common.validators.MaxFileSizeInMbImageValidator(5)]),
        ),
    ]
