# Generated by Django 4.0.4 on 2022-05-12 13:45

import django.core.validators
from django.db import migrations, models
import habibas_blog.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_blogowner_first_name_alter_blogowner_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogowner',
            name='first_name',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(2), habibas_blog.common.validators.validate_only_letters]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogowner',
            name='last_name',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(2), habibas_blog.common.validators.validate_only_letters]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownerarticle',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
