# Generated by Django 4.0.4 on 2022-05-15 19:17

from django.db import migrations, models
import habibas_blog.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_blogowner_first_name_alter_blogowner_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerarticle',
            name='image_local',
            field=models.ImageField(blank=True, null=True, upload_to='articles_local_images', validators=[habibas_blog.common.validators.MaxFileSizeInMbImageValidator(5)]),
        ),
    ]
